language: cpp
before_install:
  - sudo apt-get install -y libboost-all-dev
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y libegl1-mesa-dev libgles2-mesa-dev
  - sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev libmikmod2-dev msttcorefonts
script:
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=Release -D TREAT_WARNINGS_AS_ERRORS=1 .. 
  - make -j 2
  - ctest --output-on-failure

